### ISSUE TITLE
help in installation 

### ISSUE THREAD

**Issue by Maxywxxxx** [conradkirschner/awesome-bots-berlin#4]
Hi hi, could you help me install bot berlin-apartments-lambda, I have no idea what to use to get it and instructions there doesn’t say much to me(I never rly coded)

**Comment by conradkirschner** [comment]
This project is just a List of Project, for specific issues with one of the projects. Please raise in issue in their issue tracker 
https://github.com/AvraamMavridis/berlin-apartments-lambda-public/issues
